---
title: "Introduction to lcars"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to lcars}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, comment = "#>", out.width = "100%", message = FALSE, warning = FALSE, error = FALSE
)
```

```{r ex-1}
library(lcars)
library(ggplot2)
library(grid)
library(png)

logo <- rasterGrob(readPNG(system.file("stlogo-white.png", package = "lcars")))
clrs <- c("firebrick1", "#FFFF33", "lightseagreen")

g <- ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) + 
  geom_point() + 
  theme_lcars_dark() + 
  coord_cartesian(clip = "off") +
  annotation_custom(logo, xmin = 9.4, xmax = Inf, ymin = 3.6, ymax = Inf) +
  scale_color_manual(values = clrs)

len_frac <- c(0.55, 0.25, 0.2, 0.4, 0.1, 0.2, 0.1, 0.1)
n_seg <- c(1, 2, 0, 8)
corner_colors = c("#CD6363", "#CC99CC", "#FFFF9C", "#FFFF9C")
side_colors <- list("#FFFF9C", c("#99CCFF", "#CC99CC"), NA, 
                    c(rep("#99CCFF", 3), rep("#FF9E63", 5)))
side_labels <- list(
  "R 47.0.2", c("47", "B4"), NA, 
  c("LCARS", "47174-A", "...", "O'Brien", "Lefler", "La Forge", "Barclay", "Argyle"))

lcars_border(g, corners = 1:3, length_frac = len_frac, side_n_segments = n_seg, 
             corner_color = corner_colors, side_color = side_colors, 
             side_label = side_labels, label_size = 0.7)
text(2.8, 0.1, "Iris dataset (classic Terran flora sample)", col = "#99CCFF", font = 2, cex = 0.7)
text(7.55, 0.1, "LCARS BETA R Interface v0.0.1", col = "#FFFF9C", font = 2, cex = 0.7)
```
